### ISSUE TITLE
Open-source license

### ISSUE THREAD

**Issue by saadfarooq** [xemantic/xemantic-kotlin-swing-dsl#1]
Would you consider using a more permissible license? The applicability of LGPL in Java land is complicated since most dependencies are packaged together in a single archive and that could violate the dynamic linking requirement.

**Comment by morisil** [comment]
I am quite political about licenses, actually now more than ever. Usually my open source projects are tools for a very specific purpose and I am the only contributor. So if someone finds them useful and time saving in their commercial projects, they can contact me for a separate commercial double-license. It has happened already several times. GPL is a tool of protecting our freedom and interests, while sharing our work with the world. I especially publish JavaScript code on GPL, in contrary to popular opinions about it. Please take a look at my inspiration - Flickity licensing model:

https://flickity.metafizzy.co/

**Comment by saadfarooq** [comment]
Of course that's your choice. My concern is more that I can't use this library as a dependency in an open source project on Github that I want to distribute without restrictions unless I make that project also adhere to LGPL, even thought I'd just be using the Swing DSL as a dependency. But as I said, it's your choice.
